// Generated by Wrangler on Mon Jul 15 2024 11:21:19 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	INFOBOT_KV: KVNamespace;
	SERVICE_HOST: "https://mi.kuropen.org";
	STATUS_PAGE_HOST: "https://status.kuropen.org";
	SERVICE_NAME: "MICROPEN";
	PLATFORM_NAME: "Misskey";
	PROCESSED_ENTRIES_KV_KEY: "processed-entries";
	TEST_MODE: false;
	ALLOW_EXEC_VIA_HTTP: false;
	MISSKEY_API_TOKEN: string;
	BROWSER: Fetcher;
}
