// Generated by Wrangler on Mon Jul 15 2024 06:19:39 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	INFOBOT_KV: KVNamespace;
	SERVICE_HOST: "https://mi.kuropen.org";
	STATUS_PAGE_HOST: "https://status.kuropen.org";
	SERVICE_NAME: "MICROPEN";
	PLATFORM_NAME: "Misskey";
	TEST_MODE: false;
	MISSKEY_API_TOKEN: string;
}
