#:schema node_modules/wrangler/config-schema.json
name = "micropen-maintenance-info-bot"
main = "src/index.ts"
compatibility_date = "2024-07-12"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["*/15 * * * *"] # */15 * * * * = run 4 times an hour

[[kv_namespaces]]
binding = "INFOBOT_KV"
id = "630cbc3291b246ad822d10694873d07c"
preview_id = "9340a321a6b949faa6bd0f935a42432c"

[vars]
SERVICE_HOST = "https://mi.kuropen.org"
STATUS_PAGE_HOST = "https://status.kuropen.org"
SERVICE_NAME = "MICROPEN"
PLATFORM_NAME = "Misskey"
TEST_MODE = false
